# Trae Rules for Frontend (Nuxt 3 Project)
name: "OpenList2Strm Frontend"
description: "Nuxt 3 frontend application for OpenList2Strm"

# Project structure
structure:
  # Core Nuxt files
  - path: "app.vue"
    description: "Main application component"
    type: "component"
  
  - path: "nuxt.config.ts"
    description: "Nuxt configuration file"
    type: "config"
  
  # Standard Nuxt directories (will be created as needed)
  - path: "pages/"
    description: "Vue pages for file-based routing"
    type: "directory"
    optional: true
  
  - path: "components/"
    description: "Vue components"
    type: "directory"
    optional: true
  
  - path: "layouts/"
    description: "Application layouts"
    type: "directory"
    optional: true
  
  - path: "composables/"
    description: "Vue composables"
    type: "directory"
    optional: true
  
  - path: "utils/"
    description: "Utility functions"
    type: "directory"
    optional: true
  
  - path: "plugins/"
    description: "Nuxt plugins"
    type: "directory"
    optional: true
  
  - path: "middleware/"
    description: "Route middleware"
    type: "directory"
    optional: true
  
  - path: "assets/"
    description: "Static assets (CSS, images, etc.)"
    type: "directory"
    optional: true
  
  - path: "public/"
    description: "Public static files"
    type: "directory"
  
  - path: "server/"
    description: "Server-side code"
    type: "directory"

# File patterns and conventions
patterns:
  # Vue files
  - pattern: "**/*.vue"
    description: "Vue single file components"
    rules:
      - "Use PascalCase for component names"
      - "Include proper TypeScript types"
      - "Follow Vue 3 Composition API patterns"
  
  # TypeScript files
  - pattern: "**/*.ts"
    description: "TypeScript files"
    rules:
      - "Use proper TypeScript types"
      - "Export types and interfaces"
      - "Follow camelCase naming convention"
  
  # Configuration files
  - pattern: "*.config.ts"
    description: "Configuration files"
    rules:
      - "Use proper TypeScript configuration"
      - "Include necessary comments"

# Development guidelines
guidelines:
  - "Use TypeScript for all new code"
  - "Follow Vue 3 Composition API patterns"
  - "Use Nuxt 3 auto-imports when possible"
  - "Implement proper error handling"
  - "Use semantic HTML and accessibility best practices"
  - "Follow responsive design principles"
  - "Use proper SEO meta tags"
  - "CRITICAL: Never modify project configuration files (nuxt.config.ts, package.json, tsconfig.json, etc.) without explicit user confirmation"

# Dependencies
dependencies:
  required:
    - "nuxt"
    - "vue"
    - "vue-router"
  
  development:
    - "@nuxt/devtools"

# Build and deployment
build:
  output: ".output/"
  commands:
    dev: "npm run dev"
    build: "npm run build"
    preview: "npm run preview"

# Environment
environment:
  node_version: ">=18.0.0"
  package_manager: "npm"